server: # REST and WS server
  port: DYNAMICPORT
  address: 0.0.0.0

lavalink:
  server:
    password: "youshallnotpass"
    playerUpdateInterval: 1
    koe:
      useEpoll: true
      highPacketPriority: true
      bufferDurationMs: 400
      byteBufAllocator: "default"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: false
    lavaplayer:
      nonAllocating: false 
      frameBufferDuration: 5000 
      youtubePlaylistLoadLimit: 10 
      gc-warnings: true
      youtubeSearchEnabled: true
      soundcloudSearchEnabled: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  file:
    max-history: 30
    max-size: 5mb
  path: ./logs/

  level:
    root: INFO
    lavalink: INFO